export const GET_PROVINCES_REQUEST = "GET_PROVINCES_REQUEST";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_FAILURE = "GET_PROVINCES_FAILURE";

export const GET_DISTRICTS_REQUEST = "GET_DISTRICTS_REQUEST";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";
export const GET_DISTRICTS_FAILURE = "GET_DISTRICTS_FAILURE";

export const GET_WARDS_REQUEST = "GET_WARDS_REQUEST";
export const GET_WARDS_SUCCESS = "GET_WARDS_SUCCESS";
export const GET_WARDS_FAILURE = "GET_WARDS_FAILURE";

export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const GET_SHIPPING_FEE_REQUEST = "GET_SHIPPING_FEE_REQUEST";
export const GET_SHIPPING_FEE_SUCCESS = "GET_SHIPPING_FEE_SUCCESS";
export const GET_SHIPPING_FEE_FAILURE = "GET_SHIPPING_FEE_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const INITIATE_MOMO_PAYMENT_REQUEST = "INITIATE_MOMO_PAYMENT_REQUEST";
export const INITIATE_MOMO_PAYMENT_SUCCESS = "INITIATE_MOMO_PAYMENT_SUCCESS";
export const INITIATE_MOMO_PAYMENT_FAILURE = "INITIATE_MOMO_PAYMENT_FAILURE";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILURE = "GET_USER_ORDERS_FAILURE";
