// GET ALL
export const GET_CUSTOM_CATEGORIES_REQUEST = "GET_CUSTOM_CATEGORIES_REQUEST";
export const GET_CUSTOM_CATEGORIES_SUCCESS = "GET_CUSTOM_CATEGORIES_SUCCESS";
export const GET_CUSTOM_CATEGORIES_FAILURE = "GET_CUSTOM_CATEGORIES_FAILURE";

// GET ACTIVE
export const GET_ACTIVE_CUSTOM_CATEGORIES_REQUEST =
    "GET_ACTIVE_CUSTOM_CATEGORIES_REQUEST";
export const GET_ACTIVE_CUSTOM_CATEGORIES_SUCCESS =
    "GET_ACTIVE_CUSTOM_CATEGORIES_SUCCESS";
export const GET_ACTIVE_CUSTOM_CATEGORIES_FAILURE =
    "GET_ACTIVE_CUSTOM_CATEGORIES_FAILURE";

// CREATE
export const CREATE_CUSTOM_CATEGORY_REQUEST = "CREATE_CUSTOM_CATEGORY_REQUEST";
export const CREATE_CUSTOM_CATEGORY_SUCCESS = "CREATE_CUSTOM_CATEGORY_SUCCESS";
export const CREATE_CUSTOM_CATEGORY_FAILURE = "CREATE_CUSTOM_CATEGORY_FAILURE";

// UPDATE
export const UPDATE_CUSTOM_CATEGORY_REQUEST = "UPDATE_CUSTOM_CATEGORY_REQUEST";
export const UPDATE_CUSTOM_CATEGORY_SUCCESS = "UPDATE_CUSTOM_CATEGORY_SUCCESS";
export const UPDATE_CUSTOM_CATEGORY_FAILURE = "UPDATE_CUSTOM_CATEGORY_FAILURE";

// DELETE
export const DELETE_CUSTOM_CATEGORY_REQUEST = "DELETE_CUSTOM_CATEGORY_REQUEST";
export const DELETE_CUSTOM_CATEGORY_SUCCESS = "DELETE_CUSTOM_CATEGORY_SUCCESS";
export const DELETE_CUSTOM_CATEGORY_FAILURE = "DELETE_CUSTOM_CATEGORY_FAILURE";
